# 11. NumPy

In [2]:
import numpy as np

In [1]:
import numpy as np

# create array using np
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
a = [1,2,3,'a',5.2]
b = np.array(a)
print(b)

['1' '2' '3' 'a' '5.2']


In [7]:
a = [1,2,3,5.2]
b = np.array(a,dtype = float)
print(b)

[1.  2.  3.  5.2]


In [8]:
a = [1,2,3,'a',5.2]
b = np.array(a*3)
print(b)

['1' '2' '3' 'a' '5.2' '1' '2' '3' 'a' '5.2' '1' '2' '3' 'a' '5.2']


In [13]:
b = np.ones(3)
print(b)
c = np.ones(3,dtype = int)
print(c)

[1. 1. 1.]
[1 1 1]


In [14]:
b = np.zeros(3)
print(b)
c = np.zeros(3,dtype = int)
print(c)

[0. 0. 0.]
[0 0 0]


In [17]:
# 2d array
c = np.ones((2,3),dtype = int)
c

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
c = np.zeros((3,4),dtype = int)
print(c)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [22]:
b = np.full(3,9,dtype = float)
b

array([9., 9., 9.])

In [24]:
b = np.full((3,4),9,dtype = float)
b

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [18]:
b = np.empty((3,3))
b

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 6.265e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [20]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b = np.arange(1,11,2)
b

array([1, 3, 5, 7, 9])

In [25]:
b = np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [28]:
b = np.linspace(2,10,5,dtype = int,endpoint = False)
b

array([2, 3, 5, 6, 8])

In [30]:
b = np.identity(3,dtype = int)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Assigment Problem 

In [28]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a = np.arange(10) * 1
a = 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])