# 11. NumPy

In [1]:
import numpy as np

In [2]:
import numpy as np

# create array using np
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1,2,3,'a',5.2]
b = np.array(a)
print(b)

['1' '2' '3' 'a' '5.2']


In [4]:
a = [1,2,3,5.2]
b = np.array(a,dtype = float)
print(b)

[1.  2.  3.  5.2]


In [5]:
a = [1,2,3,'a',5.2]
b = np.array(a*3)
print(b)

['1' '2' '3' 'a' '5.2' '1' '2' '3' 'a' '5.2' '1' '2' '3' 'a' '5.2']


In [6]:
b = np.ones(3)
print(b)
c = np.ones(3,dtype = int)
print(c)

[1. 1. 1.]
[1 1 1]


In [7]:
b = np.zeros(3)
print(b)
c = np.zeros(3,dtype = int)
print(c)

[0. 0. 0.]
[0 0 0]


In [8]:
# 2d array
c = np.ones((2,3),dtype = int)
c

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
c = np.zeros((3,4),dtype = int)
print(c)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
b = np.full(3,9,dtype = float)
b

array([9., 9., 9.])

In [11]:
b = np.full((3,4),9,dtype = float)
b

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [12]:
b = np.empty((3,3))
b

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  6.38332814e-321],
       [ 5.98150141e-154, -1.69759663e-311,  3.83819576e+151]])

In [13]:
b = np.arange(10) # end point not inclusive
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.arange(1,11,2)
b

array([1, 3, 5, 7, 9])

In [15]:
b = np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [16]:
b = np.linspace(2,10,5,dtype = int,endpoint = True) # end point inclusive
b

array([ 2,  4,  6,  8, 10])

In [17]:
b = np.identity(3,dtype = int) # only generate sqaure matrix(n x n)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
b = np.eye(3,dtype = int)  # generate any matrix(n x m)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
b = np.random.rand(3) # range 0 to 1
b

array([0.59356398, 0.64099128, 0.05115084])

In [34]:
b = np.random.rand(2,3) # range 0 to 1
b

array([[0.61371332, 0.50312177, 0.16849712],
       [0.53279439, 0.25069826, 0.04660084]])

In [37]:
b = np.random.rand(10) * 10 # range 0 to 1
b

array([3.02725739, 8.48553934, 5.48205724, 7.79862928, 3.00226321,
       5.36991624, 5.86897075, 7.08340834, 5.41932375, 5.54689119])

In [79]:
b = np.random.randint(2)# genrate random number less than mentioned num
b

1

In [91]:
b = np.random.randint(25,size = (4,4))
b

array([[ 1, 24, 15,  3],
       [22, 20, 24, 22],
       [22,  1,  3,  5],
       [ 0, 19, 24, 14]])

### Slicing and Indexing In Numpy Array's

In [21]:
# 1d numpy array
a = [1,2,3,4]
arr = np.array(a)

print(a)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [22]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(4,)
int32
(4,)


In [23]:
# indexing
print(a[2])
print(arr[2])
# slicing
print(a[1:4])
print(arr[1:4])

3
3
[2, 3, 4]
[2 3 4]


In [24]:
# 2d numpy array
a = [[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]]
arr = np.array(a)

print(a)
print(arr)

[[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [25]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(4, 4)
int32
(16, 4)


In [26]:
# indexing
print(a[2][1])
print(arr[2][1])
#or
print(arr[2,1])

# slicing

# column varies 
print(arr[1][:3])
#or
print(arr[1,:3])

# row varies
print(arr[:3][2]) # wrong
print(arr[0:3,2]) # correct

# imp
print(arr[2:4,1:3])

9
9
9
[4 5 6]
[4 5 6]
[ 8  9 10 11]
[ 3  6 10]
[[ 9 10]
 [13 14]]


### Mathematical Operation

In [27]:
lis = [1,2,3,4]
np_arr_1 = np.random.randint(1,20,5)
np_arr_2 = np.random.randint(1,20,5)

print(lis)
print(np_arr_1)
print(np_arr_2)

[1, 2, 3, 4]
[ 7 13 15  8 11]
[17 13 12  5  2]


In [28]:
# adding 
#list
lis = [i+1 for i in lis]
print(lis)
#numpy
np_arr_1 = np_arr_1 +1
print(np_arr_1)

[2, 3, 4, 5]
[ 8 14 16  9 12]


In [29]:
# elemrnt by ele addition in bte two numpy
c = np_arr_1 + np_arr_2
print(c)
c = np_arr_1 - np_arr_2
print(c)
c = np_arr_1 * np_arr_2
print(c)
c = np_arr_1 / np_arr_2
print(c)
c = np_arr_1 // np_arr_2
print(c)
c = np_arr_1 % np_arr_2
print(c)
c = np_arr_1 ** np_arr_2
print(c)

[25 27 28 14 14]
[-9  1  4  4 10]
[136 182 192  45  24]
[0.47058824 1.07692308 1.33333333 1.8        6.        ]
[0 1 1 1 6]
[8 1 4 4 0]
[        0 521986048         0     59049       144]


In [30]:
print(np_arr_1.sum())
print(np_arr_1.mean())
print(np_arr_1.min())
print(np_arr_1.max())
print(np_arr_1.argmax())


59
11.8
8
16
2


In [31]:
print(np_arr_1)
print(np_arr_2)

[ 8 14 16  9 12]
[17 13 12  5  2]


In [32]:
np_arr_1 > np_arr_2

array([False,  True,  True,  True,  True])

In [33]:
np_arr_1 < np_arr_2

array([ True, False, False, False, False])

In [34]:
np_arr_1 == np_arr_2

array([False, False, False, False, False])

In [35]:
print(np.logical_or(np_arr_1 , np_arr_2))
print(np.logical_and(np_arr_1 , np_arr_2))
print(np.logical_not(np_arr_1 , np_arr_2))

[ True  True  True  True  True]
[ True  True  True  True  True]
[0 0 0 0 0]


In [36]:
a = np.array(['a','b','c','d','e','f'])
b = np.random.randint(1,20,8)

print(a)
print(b)

['a' 'b' 'c' 'd' 'e' 'f']
[12  5  2 16 13 12 12 11]


In [37]:
print(b > 10)

[ True False False  True  True  True  True  True]


### Boolean Indexing 1-d

In [72]:
bool_arr = b > 5
print(bool_arr)
new_arr = b[bool_arr] #only true value get stored in new new_arr
print(new_arr)

# shortcuts of doing this
newwst_arr = b[b>5]
print(newwst_arr)

[ True False False  True  True  True False  True]
[12 12 19 12  8]
[12 12 19 12  8]


In [75]:
arr1 = b[(b>5) & (b < 10)]
arr1

array([8])

In [38]:
print(b)
c = b
c

[12  5  2 16 13 12 12 11]


array([12,  5,  2, 16, 13, 12, 12, 11])

In [41]:
c[:3] = 19
print(c)
c[c>10] = 5
print(c)

# get index of satified value
ind = np.where(c == 5)
print(ind)
print(c[ind])

[19 19 19  5  5  5  5  5]
[5 5 5 5 5 5 5 5]
(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)
[5 5 5 5 5 5 5 5]


In [42]:
print(a)
print(b)

['a' 'b' 'c' 'd' 'e' 'f']
[5 5 5 5 5 5 5 5]


### Boolean Indexing 2-d

In [43]:
a = np.random.randint(1,30,(5,6))
a

array([[ 4,  8, 17, 27, 18, 27],
       [ 4,  6, 29, 15, 21,  1],
       [21, 17, 19,  1,  9, 16],
       [ 5,  5, 17, 28, 20, 19],
       [14, 10, 13, 14,  9, 10]])

In [44]:
bool_arr = a>20
bool_arr


array([[False, False, False,  True, False,  True],
       [False, False,  True, False,  True, False],
       [ True, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False]])

In [45]:
ans = a[bool_arr]
ans

array([27, 27, 29, 21, 21, 28])

In [46]:
b = a


In [47]:
b[bool_arr] = 100
print(b)

[[  4   8  17 100  18 100]
 [  4   6 100  15 100   1]
 [100  17  19   1   9  16]
 [  5   5  17 100  20  19]
 [ 14  10  13  14   9  10]]


In [48]:
c = np.random.randint(1,10,(2,2))
print(c)

[[8 5]
 [9 2]]


In [49]:
c_bool = np.random.randint(1,10,(3,2))
c_bool

array([[6, 2],
       [3, 2],
       [6, 7]])

In [50]:
print(c[c_bool])

IndexError: index 6 is out of bounds for axis 0 with size 2

In [51]:
print(b)

[[  4   8  17 100  18 100]
 [  4   6 100  15 100   1]
 [100  17  19   1   9  16]
 [  5   5  17 100  20  19]
 [ 14  10  13  14   9  10]]


In [52]:
b_bool = b[:,3] == 100
print(b_bool)

[ True False False  True False]


In [53]:
b[b_bool,3] = 0
print(b)

[[  4   8  17   0  18 100]
 [  4   6 100  15 100   1]
 [100  17  19   1   9  16]
 [  5   5  17   0  20  19]
 [ 14  10  13  14   9  10]]


### Real World Example using dataet "year2017"

In [54]:
import csv
import numpy as np

file_name = open("Dataset/year2017.csv")
file_data = csv.DictReader(file_name, skipinitialspace = True)
    
killed = []
wound = []
country = []
for row in file_data:
    killed.append(row['Killed'])
    wound.append(row['Wounded'])
    country.append(row['Country'])

# converting to array
np_killed = np.array(killed)
np_wound = np.array(wound)

# replacing empty string with '0.0'
np_killed[np_killed == ''] = '0.0'
np_wound[np_wound == ''] = '0.0'

# converting to string to float
np_killed = np.array(np_killed,dtype = float)
np_wound = np.array(np_wound,dtype = float)

# killed + wounded
killed_wounded = np_killed + np_wound
print(np.sum(killed_wounded))

# *****sol completed *****
# extra
np_country = np.array(country)
bool_arr = np_country == "India"
ans = killed_wounded[bool_arr]
print(np.sum(ans))


51372.0
1167.0


### Assigment Problem 

In [28]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a = np.arange(10) * 1
a = 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a = np.linspace(9,49,40,dtype = int)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 49])

In [89]:
a = np.eye(5,6,dtype = int)
a

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [27]:
a = np.linspace(0,5,9)
a

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [86]:
arr = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
np_arr = np.array(arr)

print(np_arr)
# question 1
print(f"solution 1 : {np_arr[2, :3]}")
# question 2
print(f"solution 2 : {np_arr[1:4 ,3]}")
# question 3
print(f"solution 3 : {np_arr[2:4, :5]}")
# question 4
print(f"solution 4 : {np_arr[1:3, 1:3]}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
solution 1 : [11 12 13]
solution 2 : [ 9 14 19]
solution 3 : [[11 12 13 14 15]
 [16 17 18 19 20]]
solution 4 : [[ 7  8]
 [12 13]]


In [88]:
a = [1,2,0,0,4,0] # non zero index
np_arr = np.array(a)

c = np_arr

ind = np.where(c != 0)
ind

(array([0, 1, 4], dtype=int64),)

In [90]:
a = [1,3,5,7,9,11,13,15,17,19] # multiple of 3 index
np_arr = np.array(a)

c = np_arr

ind = np.where(c % 3 == 0)
ind

(array([1, 4, 7], dtype=int64),)

In [93]:
a = [1,2,3,4,5,6,7,8,9,10] # replace odd with -1
np_arr = np.array(a)

np_arr[np_arr%2 != 0] = -1
np_arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [95]:
a = [11,2,13,4,15,6,27,8,19] # replace first max occerance with zeros
np_arr = np.array(a)

np_arr[np_arr.argmax()] = 0
np_arr

array([11,  2, 13,  4, 15,  6,  0,  8, 19])

In [100]:
a = [1,2,3,4,5,6,7,8,9,10] # replace odd with -1
np_arr = np.array(a)

c = np_arr[(np_arr >= 3) & (np_arr <= 8)]
c

array([3, 4, 5, 6, 7, 8])

In [115]:
age = np.random.randint(6,9,20,dtype = int)
height = np.random.randint(120,190,20,dtype = int)
print(age)
print(height)

[7 8 6 6 6 8 8 7 6 8 7 8 8 6 8 7 6 8 7 6]
[174 120 179 172 138 140 142 129 124 144 181 152 165 186 185 148 182 178
 156 185]


In [134]:
print(age[height>155])
c = age[height>155]
print(np.where(c))


[7 6 6 7 8 6 8 6 8 7 6]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)
