# 11. NumPy

In [1]:
import numpy as np

In [1]:
import numpy as np

# create array using np
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
a = [1,2,3,'a',5.2]
b = np.array(a)
print(b)

['1' '2' '3' 'a' '5.2']


In [7]:
a = [1,2,3,5.2]
b = np.array(a,dtype = float)
print(b)

[1.  2.  3.  5.2]


In [8]:
a = [1,2,3,'a',5.2]
b = np.array(a*3)
print(b)

['1' '2' '3' 'a' '5.2' '1' '2' '3' 'a' '5.2' '1' '2' '3' 'a' '5.2']


In [13]:
b = np.ones(3)
print(b)
c = np.ones(3,dtype = int)
print(c)

[1. 1. 1.]
[1 1 1]


In [14]:
b = np.zeros(3)
print(b)
c = np.zeros(3,dtype = int)
print(c)

[0. 0. 0.]
[0 0 0]


In [17]:
# 2d array
c = np.ones((2,3),dtype = int)
c

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
c = np.zeros((3,4),dtype = int)
print(c)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [22]:
b = np.full(3,9,dtype = float)
b

array([9., 9., 9.])

In [24]:
b = np.full((3,4),9,dtype = float)
b

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [18]:
b = np.empty((3,3))
b

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 6.265e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [20]:
b = np.arange(10) # end point not inclusive
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b = np.arange(1,11,2)
b

array([1, 3, 5, 7, 9])

In [25]:
b = np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [82]:
b = np.linspace(2,10,5,dtype = int,endpoint = True) # end point inclusive
b

array([ 2,  4,  6,  8, 10])

In [30]:
b = np.identity(3,dtype = int) # only generate sqaure matrix(n x n)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [31]:
b = np.eye(3,dtype = int)  # generate any matrix(n x m)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
b = np.random.rand(3) # range 0 to 1
b

array([0.59356398, 0.64099128, 0.05115084])

In [34]:
b = np.random.rand(2,3) # range 0 to 1
b

array([[0.61371332, 0.50312177, 0.16849712],
       [0.53279439, 0.25069826, 0.04660084]])

In [37]:
b = np.random.rand(10) * 10 # range 0 to 1
b

array([3.02725739, 8.48553934, 5.48205724, 7.79862928, 3.00226321,
       5.36991624, 5.86897075, 7.08340834, 5.41932375, 5.54689119])

In [79]:
b = np.random.randint(2)# genrate random number less than mentioned num
b

1

In [91]:
b = np.random.randint(25,size = (4,4))
b

array([[ 1, 24, 15,  3],
       [22, 20, 24, 22],
       [22,  1,  3,  5],
       [ 0, 19, 24, 14]])

### Slicing and Indexing In Numpy Array's

In [11]:
# 1d numpy array
a = [1,2,3,4]
arr = np.array(a)

print(a)
print(arr)

[1, 2, 3, 4]
[1 2 3 4]


In [13]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(4,)
int32
(4,)


In [16]:
# indexing
print(a[2])
print(arr[2])
# slicing
print(a[1:4])
print(arr[1:4])

3
3
[2, 3, 4]
[2 3 4]


In [17]:
# 2d numpy array
a = [[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]]
arr = np.array(a)

print(a)
print(arr)

[[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [18]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(4, 4)
int32
(16, 4)


In [26]:
# indexing
print(a[2][1])
print(arr[2][1])
#or
print(arr[2,1])

# slicing

# column varies 
print(arr[1][:3])
#or
print(arr[1,:3])

# row varies
print(arr[:3][2]) # wrong
print(arr[0:3,2]) # correct

# imp
print(arr[2:4,1:3])

9
9
9
[4 5 6]
[4 5 6]
[ 8  9 10 11]
[ 3  6 10]
[[ 9 10]
 [13 14]]


### Assigment Problem 

In [28]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a = np.arange(10) * 1
a = 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a = np.linspace(9,49,40,dtype = int)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 49])

In [89]:
a = np.eye(5,6,dtype = int)
a

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [90]:
a = np.linspace(0,5,9)
a

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])